// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MyEarthLocation struct {
	ID              int32
	City            string
	WeatherSummary  pgtype.Text
	Temperature     pgtype.Float4
	WindSpeed       pgtype.Float4
	WindAngle       pgtype.Float4
	WindDirection   pgtype.Text
	Latitude        pgtype.Float8
	Longitude       pgtype.Float8
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	ExpiredAt       pgtype.Timestamptz
	TemperatureUnit pgtype.Text
}
