services:
  my-earth:
   image: earth-server:latest
   deploy:
     resources:
       limits:
         memory: 125M
   env_file: ./envs/earth.env
   ports:
     - "8080:8080"
  postgres:
    image: postgres:12.19
    deploy:
      resources:
        limits:
          memory: 125M
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
      PGDATA: /var/lib/pg_data
    volumes:
      - ./db/postgres/init:/docker-entrypoint-initdb.d
      - ./.volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      